In [9]:
import os
import pandas as pd
import sys

current_directory =  os.getcwd()
parent_directory = os.path.dirname(current_directory)
modules_folder = os.path.join(parent_directory, 'modules_folderA') 

#grand_parent_directory = path.dirname(parent_directory)


sys.path.insert(0, parent_directory) # defined root folder 1 step up


#defining files for testing:
parent_folder = os.path.dirname(os.getcwd())
xlsx_file_name = 'xlsx_file.xlsx'
csv_file_name = 'csv_file.csv'
xlsx_file_path = os.path.join(current_folder, '..', 'test_files', xlsx_file_name)
csv_file_path = os.path.join(current_folder, '..', 'test_files', csv_file_name)
txt_file_path = os.path.join(current_folder, '..', 'test_files', 'txt_file.csv')
csv_file_path[-4:]=='.csv'

True

In [10]:
path_to_add_to_sys = os.path.join(os.getcwd(), '..', 'experiments')
sys.path.insert(0,path_to_add_to_sys)
from test_class1 import test_class1

In [11]:
object_of_class = test_class1(txt_file_path)

.csv


In [12]:
import numpy as np
x = np.random.randn(2,30)
x += np.array([[55],[66]])
x

array([[54.3636158 , 54.82508441, 55.95508972, 55.96538199, 54.06238808,
        55.12448371, 54.1273898 , 53.87419297, 54.55733883, 53.69266529,
        53.57837984, 54.37203659, 54.29636481, 55.69101252, 55.71405874,
        54.26998906, 57.00023632, 55.55251126, 57.27644528, 54.86386548,
        54.47947683, 55.3225053 , 55.64570706, 54.70912786, 55.64217475,
        56.1395378 , 55.12055449, 55.68108736, 53.98208287, 54.1039904 ],
       [67.24663045, 64.9144682 , 64.60307316, 65.91560636, 66.60077603,
        67.01184313, 65.87114903, 67.19608408, 65.96507096, 66.17958508,
        64.53372514, 66.43657362, 64.1086155 , 66.02209088, 65.96623371,
        65.73193343, 66.38652063, 65.42079165, 65.42739151, 65.63585954,
        67.34636987, 66.27957008, 65.2149909 , 65.83273982, 66.8277381 ,
        66.33102454, 67.48443093, 69.0620113 , 66.59592392, 67.64483203]])

In [18]:
    data_2d=np.random.randn(2, 30)
    data_2d[:500] -= np.array([[-2],[-4]])
    data_2d[500:] += np.array([[2],[3]])

ValueError: operands could not be broadcast together with shapes (0,30) (2,1) (0,30) 

In [26]:
    x1 = np.random.normal(-2,1,700)
    x2 = np.random.normal(2.5,3,150)
    x = np.append(x1, x2)
    np.random.shuffle(x)
    y1 = np.random.normal(-2,0.5,700)
    y2 = np.random.normal(2.5,1,150)
    y = np.append(y1, y2)
    data_2d = np.array([x,y])
    data_2d

array([[-1.01967016, -0.77467156, -1.34216092, ...,  0.36886943,
        -0.41072036,  5.52630653],
       [-2.46768873, -1.74356924, -1.42749123, ...,  3.19517591,
         3.15252437,  3.11470464]])

In [1]:
def get_2d_distr_with_outliers():
    x1 = np.random.normal(-2,1,700)
    x2 = np.random.normal(2.5,3,150)
    x = np.append(x1, x2)
    np.random.shuffle(x)
    y1 = np.random.normal(-2,0.5,700)
    y2 = np.random.normal(2.5,1,150)
    y = np.append(y1, y2)
    np.random.shuffle(y)
    data_2d = np.array([x,y])
    return data_2d

x1 = get_2d_distr_with_outliers()
x1[0]

NameError: name 'np' is not defined

In [12]:
from src.data_processing.DataReader import DataReader
object_of_class = DataReader(txt_file_path)
object_of_class.get_user_data_df()

c:\Users\Savvas\Documents\Projects\AnomalyDetectionTool\notebooks\..\test_files\txt_file.csv


FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\Savvas\\Documents\\Projects\\AnomalyDetectionTool\\notebooks\\..\\test_files\\txt_file.csv'

In [56]:
import numpy as np
ind = np.array([0,1,2,3])
ind.shape = (4,1)
ind

arr=np.array([10,11,12,13,14,15,16,17])
arr.shape = (4,2)
arr

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [54]:
len(arr)

7

In [48]:
cond = arr>3
cond

array([[False],
       [ True],
       [ True]])

In [49]:
ind[cond]

array([1, 2])

In [50]:
arr[ind[cond],:]

array([[5],
       [7]])

In [20]:
new_cond = 

array([2, 3])

In [32]:
arr

array([[3],
       [5],
       [7]])

In [35]:
arr[ind[condition],:]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [24]:
arr

array([[3],
       [5],
       [7]])

[[ 2]
 [16]
 [ 0]
 [ 9]
 [ 2]
 [13]
 [ 8]
 [ 4]
 [19]
 [14]
 [ 6]
 [12]
 [10]
 [ 3]
 [15]
 [ 2]
 [18]
 [ 4]
 [17]
 [13]]


In [14]:
3 in [3,4,5]

True

In [23]:
a = np.array([3,4,5,6])
np.invert(a>4)
a[np.invert(a>4)]

array([3, 4])

In [34]:
len(data_index)
da

20

In [99]:
import numpy as np
data_index = np.arange(5).reshape((5,1))
data = np.random.randint(0,20,5).reshape(5,1)
print (f'{data=}')
print (f'{data_index=}')

data=array([[ 1],
       [ 8],
       [ 1],
       [14],
       [11]])
data_index=array([[0],
       [1],
       [2],
       [3],
       [4]])


In [133]:
def method1(data, number):
    return data<number

method1(data, 7)

array([[ True],
       [False],
       [ True],
       [False],
       [False]])

In [161]:
####Works
def iteration_method(method, data, data_index):
    new_data = np.array(data, copy=True)
    new_data_index = np.array(data_index, copy=True)
    outlier_indexes_found_after_iterations = []

    number = 7        
    outlier_positions = method(new_data, number)
    outlier_indexes = data_index[outlier_positions]
    value_positions = np.invert(outlier_positions)

    new_data_len = sum(value_positions)[0]
    num_of_outliers_found = sum(outlier_positions)[0]

    print (f'{value_positions=}')
    print (f'{outlier_positions=}')
    new_data = new_data[value_positions].reshape((new_data_len,1))
    new_data_index = new_data_index[value_positions].reshape((new_data_len,1))
    outlier_indexes_found_after_iterations.append(outlier_indexes.tolist())

    print (f'{new_data=}')
    print (f'{new_data_index=}')



    number = number+2
    outlier_positions = method(new_data, number)
    outlier_indexes = new_data_index[outlier_positions]
    value_positions = np.invert(outlier_positions)
    new_data_len = sum(value_positions)[0]
    num_of_outliers_found = sum(outlier_positions)[0]
    new_data = new_data[value_positions].reshape((new_data_len,1))
    new_data_index = new_data_index[value_positions].reshape((new_data_len,1))
    outlier_indexes_found_after_iterations.append(outlier_indexes.tolist())


    print (f'{new_data=}')
    print (f'{new_data_index=}')
    print ('-'*7)
    print(outlier_indexes_found_after_iterations)
    
    return None

iteration_method(method1, data, data_index)

value_positions=array([[False],
       [ True],
       [False],
       [ True],
       [ True]])
outlier_positions=array([[ True],
       [False],
       [ True],
       [False],
       [False]])
new_data=array([[ 8],
       [14],
       [11]])
new_data_index=array([[1],
       [3],
       [4]])
new_data=array([[14],
       [11]])
new_data_index=array([[3],
       [4]])
-------
[[0, 2], [1]]


In [60]:
np.array(['a', 'b'])

array(['a', 'b'], dtype='<U1')

In [20]:
import numpy as np
data_index = np.arange(5).reshape((5,1))
data = np.random.randint(0,20,5).reshape(5,1)
print (f'{data=}')
print (f'{data_index=}')

data=array([[ 5],
       [ 4],
       [14],
       [18],
       [11]])
data_index=array([[0],
       [1],
       [2],
       [3],
       [4]])


In [57]:
from numpy.typing import NDArray


def method1(data, number):
    return data<number

#refactoring in process
def iteration_method(method, data, data_index) -> tuple[list,list]:
    new_data = np.array(data, copy=True)
    new_data_index = np.array(data_index, copy=True)
    outlier_indexes_per_iterations = []

    number = 7
    i = 0
    while True and i<10 and len(new_data_index)>0:
        outlier_positions = method(new_data, number)
        outlier_indexes = new_data_index[outlier_positions]
        value_positions = np.invert(outlier_positions)
        new_data_len = sum(value_positions)[0]
        new_data = new_data[value_positions].reshape((new_data_len,1))
        new_data_index = new_data_index[value_positions].reshape((new_data_len,1))
        outlier_indexes_per_iterations.append(outlier_indexes.tolist())
        number = number+2
        i += 1
        
    list_all_outlier_indexes = np.concatenate(outlier_indexes_per_iterations)
    list_all_outlier_indexes = [int(i) for i in list_all_outlier_indexes]
    
    return outlier_indexes_per_iterations, list_all_outlier_indexes

test1, _ = iteration_method(method1, data, data_index)

In [ ]:
def method1_iteration(data, data_index):
    outlier_indexes_per_iterations, list_all_outlier_indexes = iteration_method(method1,data,data_index)
    


In [64]:
def combine_outlier_booleans(*arg_bool):
    """gets any number of outlier_bool from different methods and 
    combines them. It is ment to be used to combine outliers found 
    from different methods to make a list of final outliers. 

    Returns:
        _type_: np.array(booleans)
    """
    combined_outlier_bool = np.array([False]*len(arg_bool[0]))
    for bool in arg_bool:
        combined_outlier_bool[bool]=True

    return combined_outlier_bool


ar1 = np.array([True, False])
ar2 = np.array([False,True])
combine_outlier_booleans(ar1, None)

array([ True,  True])

In [69]:
test1 = np.array(['blue']*3)
mask = np.array([False,True,False])
test1[mask]
test1[mask]='red'
test1

array(['blue', 'red', 'blue'], dtype='<U4')

In [71]:
test1 = [1,2,3,4]
for i in test1:
    print (i)

1
2
3
4
